name: Vault Secret Retrieval

on:
  workflow_dispatch:

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vault Secret
        uses: hashicorp/vault-action@v2
        id: vault
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv-v2/data/myapp username

      - name: Use Retrieved Secrets
        run: |
          echo "Database password retrieved successfully: ${{ steps.vault.outputs.username }}"
          # Secrets are available as:
          # ${{ steps.vault.outputs.username }}
