name: Vault Secret Retrieval

on:
  workflow_dispatch:
    inputs:
      vault_addr:
        description: 'Vault server URL'
        required: true
        type: string
      role_name:
        description: 'Vault role name'
        required: true
        type: string
        default: 'myproject-github-role'
      env:
        description: 'Environment'
        required: true
        type: string
        default: 'dev'

# Required for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Get Vault Secret
        uses: hashicorp/vault-action@v2
        id: vault
        with:
          url: ${{ github.event.inputs.vault_addr }}
          method: jwt
          role: ${{ github.event.inputs.role_name }}
          jwtGithubAudience: https://github.com/${{ github.repository }}-ENV-${{ github.event.inputs.env }}
          tlsSkipVerify: true
          secrets: |
            kv-v2/data/myapp username

      - name: Use Retrieved Secrets
        run: |
          # This will still be masked if it matches a secret
          echo "Username: ${{ steps.vault.outputs.username }}"
          
          # Try encoding to bypass masking (for debugging only)
          echo "Username (base64): $(echo '${{ steps.vault.outputs.username }}' | base64)"
          
          # Or use printf instead of echo
          printf "Username: %s\n" '${{ steps.vault.outputs.username }}'
          # Secrets are available as:
          # ${{ steps.vault.outputs.username }}
