name: Vault Secret Retrieval

on:
  workflow_dispatch:
    inputs:
      vault_addr:
        description: 'Vault server URL'
        required: true
        type: string

# Required for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vault Secret
        uses: hashicorp/vault-action@v2
        id: vault
        with:
          url: ${{ github.event.inputs.vault_addr }}
          method: jwt
          role: myproject-github-role
          jwtGithubAudience: https://github.com/songlining/github-action-vault-demo
          tlsSkipVerify: true
          secrets: |
            kv-v2/data/myapp username

      - name: Use Retrieved Secrets
        run: |
          # This will still be masked if it matches a secret
          echo "Username: ${{ steps.vault.outputs.username }}"
          
          # Try encoding to bypass masking (for debugging only)
          echo "Username (base64): $(echo '${{ steps.vault.outputs.username }}' | base64)"
          
          # Or use printf instead of echo
          printf "Username: %s\n" '${{ steps.vault.outputs.username }}'
          # Secrets are available as:
          # ${{ steps.vault.outputs.username }}
